apiVersion: v1
kind: Pod 
metadata: 
  name: test
  labels: 
    app: dev
spec:
  containers:
  - name: test
    # image: minhvhn/mqtt-clients:v1.1
    image: minhvhn/tcp-clients:v1.1
    ports: 
    - containerPort: 65432
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  ports:
  - protocol: TCP
    port: 65432
    targetPort: 65432
  selector:
    app: dev
  
