version: '3.8'

services:
  # Mosquitto broker
  broker:
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - ./broker/config:/mosquitto/config
      - ./broker/data:/mosquitto/data
      - ./broker/log:/mosquitto/log    
    ports:
      - 1883:1883
      - 9001:9001
    container_name: broker

  